
kind: ReplicationController
apiVersion: v1
metadata:
  name: gceme-backend
spec:
  replicas: 1
  selector:
    app: gceme
    role: backend
  template:
    metadata:
      name: backend
      labels:
        app: gceme
        role: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/cloud-solutions-images/gceme:1.0.0
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
        command: ["sh", "-c", "app -port=8080"]
        ports:
        - name: backend
          containerPort: 8080
