
kind: ReplicationController
apiVersion: v1
metadata:
  name: gceme-frontend
spec:
  replicas: 1
  selector:
    app: gceme
    role: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: gceme
        role: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/cloud-solutions-images/gceme:1.0.0
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
        command: ["sh", "-c", "app -frontend=true -backend-service=http://${GCEME_BACKEND_SERVICE_HOST}:${GCEME_BACKEND_SERVICE_PORT} -port=80"]
        ports:
        - name: frontend
          containerPort: 80
