---
kind: Service
apiVersion: v1
metadata:
  name: gceme-backend
  labels:
    name: gceme-backend
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    name: gceme-backend
