---
kind: Service
apiVersion: v1
metadata:
  name: gceme-frontend
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: gceme
    role: frontend
  type: LoadBalancer
