---
kind: Service
apiVersion: v1
metadata:
  name: gceme
  labels:
    name: gceme
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    name: gceme-frontend
  type: LoadBalancer
